name: gpt_detector
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.2

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter

  # State management
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.0.0

  # Networking
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  internet_connection_checker: ^1.0.0+1

  # Dependency injection
  injectable: ^2.1.0
  get_it: ^7.2.0

  # Data class generation
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

  # Functional programming
  dartz: ^0.10.1

  # Routing
  auto_route: ^5.0.4

  # Utility
  permission_handler: ^10.2.0
  device_info_plus: ^8.1.0
  image_picker: ^0.8.6+1
  image_cropper: ^3.0.1
  flutter_dotenv: ^5.0.2
  path_provider: ^2.0.12
  in_app_review: ^2.0.6
  url_launcher: ^6.1.8
  share_plus: ^6.3.1
  intl: ^0.17.0

  # OCR
  google_mlkit_text_recognition: ^0.5.0

  # Packages
  form_inputs:
    path: packages/form_inputs

  # UI
  countup: ^0.1.4
  cupertino_icons: ^1.0.2
  flutter_animate: ^3.1.0

  # App Icons
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  bloc_test: ^9.1.0

  # Code gen
  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  auto_route_generator: ^5.0.3
  injectable_generator: ^2.1.4

  # Linter
  very_good_analysis: ^4.0.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/logo.png"
  adaptive_icon_background: "#6200EE"
  # Padding 8%
  adaptive_icon_foreground: "assets/icons/logo_foreground.png"

flutter_native_splash:
  android: true
  ios: true
  android12: true
  color: "#6200EE"
  image: "assets/icons/logo_no_bg.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - env/
    - assets/icons/
